'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.18052
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 4.0.30319.18052.
'
Namespace OnlineReporting
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="StatisticsReportingSoap", [Namespace]:="http://StatisticData/")>  _
    Partial Public Class StatisticsReporting
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendApplicationMetricDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ClausSoftware.My.MySettings.Default.HWLKernel_OnlineReporting_StatisticsReporting
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendApplicationMetricDataCompleted As SendApplicationMetricDataCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://StatisticData/SendApplicationMetricData", RequestNamespace:="http://StatisticData/", ResponseNamespace:="http://StatisticData/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SendApplicationMetricData(ByVal [date] As Date, ByVal runningModule As String, ByVal instanceID As Integer, ByVal AppID As String, ByVal AppVersion As String, ByVal AppName As String, ByVal MessageType As String, ByVal text As String)
            Me.Invoke("SendApplicationMetricData", New Object() {[date], runningModule, instanceID, AppID, AppVersion, AppName, MessageType, text})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendApplicationMetricDataAsync(ByVal [date] As Date, ByVal runningModule As String, ByVal instanceID As Integer, ByVal AppID As String, ByVal AppVersion As String, ByVal AppName As String, ByVal MessageType As String, ByVal text As String)
            Me.SendApplicationMetricDataAsync([date], runningModule, instanceID, AppID, AppVersion, AppName, MessageType, text, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendApplicationMetricDataAsync(ByVal [date] As Date, ByVal runningModule As String, ByVal instanceID As Integer, ByVal AppID As String, ByVal AppVersion As String, ByVal AppName As String, ByVal MessageType As String, ByVal text As String, ByVal userState As Object)
            If (Me.SendApplicationMetricDataOperationCompleted Is Nothing) Then
                Me.SendApplicationMetricDataOperationCompleted = AddressOf Me.OnSendApplicationMetricDataOperationCompleted
            End If
            Me.InvokeAsync("SendApplicationMetricData", New Object() {[date], runningModule, instanceID, AppID, AppVersion, AppName, MessageType, text}, Me.SendApplicationMetricDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendApplicationMetricDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendApplicationMetricDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendApplicationMetricDataCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub SendApplicationMetricDataCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
