'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
'
Namespace de.shk_connect.shkgh2
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AnwenderIndividuelleAuskuenfteBeanBinding", [Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class anwenderIndividuelleAuskuenfteService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetIndividuelleAuskunftOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SHK_Connect.My.MySettings.Default.SHK_Connect_de_shk_connect_shkgh2_anwenderIndividuelleAuskuenfteService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetIndividuelleAuskunftCompleted As GetIndividuelleAuskunftCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function GetIndividuelleAuskunft(<System.Xml.Serialization.XmlElementAttribute("GetIndividuelleAuskunft", [Namespace]:="http://service.shk-connect.de")> ByVal GetIndividuelleAuskunft1 As GetIndividuelleAuskunft) As <System.Xml.Serialization.XmlElementAttribute("GetIndividuelleAuskunftAntwort", [Namespace]:="http://service.shk-connect.de")> GetIndividuelleAuskunftResponse
            Dim results() As Object = Me.Invoke("GetIndividuelleAuskunft", New Object() {GetIndividuelleAuskunft1})
            Return CType(results(0),GetIndividuelleAuskunftResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetIndividuelleAuskunftAsync(ByVal GetIndividuelleAuskunft1 As GetIndividuelleAuskunft)
            Me.GetIndividuelleAuskunftAsync(GetIndividuelleAuskunft1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetIndividuelleAuskunftAsync(ByVal GetIndividuelleAuskunft1 As GetIndividuelleAuskunft, ByVal userState As Object)
            If (Me.GetIndividuelleAuskunftOperationCompleted Is Nothing) Then
                Me.GetIndividuelleAuskunftOperationCompleted = AddressOf Me.OnGetIndividuelleAuskunftOperationCompleted
            End If
            Me.InvokeAsync("GetIndividuelleAuskunft", New Object() {GetIndividuelleAuskunft1}, Me.GetIndividuelleAuskunftOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetIndividuelleAuskunftOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetIndividuelleAuskunftCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetIndividuelleAuskunftCompleted(Me, New GetIndividuelleAuskunftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class GetIndividuelleAuskunft
        
        Private schnittstellenversionField As String
        
        Private softwarenameField As String
        
        Private softwarepasswortField As String
        
        Private unternehmensIDField As Integer
        
        Private kundennummerField As String
        
        Private benutzernameField As String
        
        Private passwortField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Schnittstellenversion() As String
            Get
                Return Me.schnittstellenversionField
            End Get
            Set
                Me.schnittstellenversionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Softwarename() As String
            Get
                Return Me.softwarenameField
            End Get
            Set
                Me.softwarenameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Softwarepasswort() As String
            Get
                Return Me.softwarepasswortField
            End Get
            Set
                Me.softwarepasswortField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UnternehmensID() As Integer
            Get
                Return Me.unternehmensIDField
            End Get
            Set
                Me.unternehmensIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kundennummer() As String
            Get
                Return Me.kundennummerField
            End Get
            Set
                Me.kundennummerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Benutzername() As String
            Get
                Return Me.benutzernameField
            End Get
            Set
                Me.benutzernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Passwort() As String
            Get
                Return Me.passwortField
            End Get
            Set
                Me.passwortField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class Link
        
        Private beschreibungField As String
        
        Private uRLField As String
        
        Private datumField As String
        
        Private groesseField As System.Nullable(Of Long)
        
        Private authentifizierungsmethodeField As Authentifizierungsmethode
        
        Private datenDatumField As String
        
        Private aenderungsInfoField As String
        
        Private cookieListField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Beschreibung() As String
            Get
                Return Me.beschreibungField
            End Get
            Set
                Me.beschreibungField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property URL() As String
            Get
                Return Me.uRLField
            End Get
            Set
                Me.uRLField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Datum() As String
            Get
                Return Me.datumField
            End Get
            Set
                Me.datumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property Groesse() As System.Nullable(Of Long)
            Get
                Return Me.groesseField
            End Get
            Set
                Me.groesseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Authentifizierungsmethode() As Authentifizierungsmethode
            Get
                Return Me.authentifizierungsmethodeField
            End Get
            Set
                Me.authentifizierungsmethodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DatenDatum() As String
            Get
                Return Me.datenDatumField
            End Get
            Set
                Me.datenDatumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AenderungsInfo() As String
            Get
                Return Me.aenderungsInfoField
            End Get
            Set
                Me.aenderungsInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Cookie", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property CookieList() As String()
            Get
                Return Me.cookieListField
            End Get
            Set
                Me.cookieListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Public Enum Authentifizierungsmethode
        
        '''<remarks/>
        URL
        
        '''<remarks/>
        HTTPAUTH
        
        '''<remarks/>
        KEINE
        
        '''<remarks/>
        COOKIE
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class Prozess
        
        Private prozesscodeField As String
        
        Private teilprozesseField() As String
        
        Private uRLField As String
        
        Private linkField() As Link
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Prozesscode() As String
            Get
                Return Me.prozesscodeField
            End Get
            Set
                Me.prozesscodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Teilprozess", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Teilprozesse() As String()
            Get
                Return Me.teilprozesseField
            End Get
            Set
                Me.teilprozesseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property URL() As String
            Get
                Return Me.uRLField
            End Get
            Set
                Me.uRLField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Link", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Link() As Link()
            Get
                Return Me.linkField
            End Get
            Set
                Me.linkField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class Status
        
        Private codeField As String
        
        Private meldungField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Meldung() As String
            Get
                Return Me.meldungField
            End Get
            Set
                Me.meldungField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class GetIndividuelleAuskunftResponse
        
        Private schnittstellenversionField As String
        
        Private serverkennungField As String
        
        Private statusField As Status
        
        Private prozesslisteField() As Prozess
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Schnittstellenversion() As String
            Get
                Return Me.schnittstellenversionField
            End Get
            Set
                Me.schnittstellenversionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Serverkennung() As String
            Get
                Return Me.serverkennungField
            End Get
            Set
                Me.serverkennungField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Status() As Status
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Prozessliste() As Prozess()
            Get
                Return Me.prozesslisteField
            End Get
            Set
                Me.prozesslisteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetIndividuelleAuskunftCompletedEventHandler(ByVal sender As Object, ByVal e As GetIndividuelleAuskunftCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetIndividuelleAuskunftCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetIndividuelleAuskunftResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetIndividuelleAuskunftResponse)
            End Get
        End Property
    End Class
End Namespace
