'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ClausSoftware.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 
        '''Sehr geehrte Damen und Herren, 
        '''
        '''bereits zweimal haben wir Sie aufgefordert den Betrag von $RB vom $RD,&quot;$RT&quot; zu begleichen.
        '''Leider konnten wir bislang noch keinen Zahlungseingang verbuchen.
        '''
        '''Wir möchten Sie bitten innerhalb von 14 Tagen den ausstehenden Betrag von $RB auf unser Konto: 
        '''$BV
        '''zu überweisen anderenfalls sehen wir uns gezwungen einen Rechtsweg einzunehmen.
        '''
        '''Sollte sich die Begleichung der Rechnung mit diesem Schreiben überschnitten haben, so betrachten Sie es als gegenstandslos.
        '''
        '''Mi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Final_Demand() As String
            Get
                Return ResourceManager.GetString("Final_Demand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 
        '''Sehr geehrte Damen und Herren, 
        '''
        '''sicher haben Sie es übersehen, aber für die Rechnung Nr. $RN, $RT vom $RD konnten wir bis heute, den $DH keinen Zahlungseingang verzeichnen.
        '''
        '''
        '''Wir möchten Sie bitten diesen Sachverhalt einmal zu überprüfen und den Betrag von $RB auf unser Konto: 
        '''$BV
        '''zu überweisen.
        '''
        '''Sollte sich die Begleichung der Rechnung mit diesem Schreiben überschnitten haben, so betrachten Sie es als gegenstandslos.
        '''
        '''Mit freundlichem Gruß,
        '''
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property First_Remind() As String
            Get
                Return ResourceManager.GetString("First_Remind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_picture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_picture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 
        '''Sehr geehrte Damen und Herren, 
        '''
        '''wir haben sie bereits am $D1M darauf hingewiesen die Rechnung Nr:$RN vom $RD zu begleichen. 
        '''Leider konnten wir bislang noch keinen Zahlungseingang verbuchen.
        '''
        '''Wir möchten Sie bitten innerhalb von 14 Tagen den ausstehenden Betrag von $RB auf unser Konto: 
        '''$BV
        '''zu überweisen.
        '''
        '''Sollte sich die Begleichung der Rechnung mit diesem Schreiben überschnitten haben, so betrachten Sie es als gegenstandslos.
        '''
        '''Mit freundlichem Gruß,
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property Second_Remind() As String
            Get
                Return ResourceManager.GetString("Second_Remind", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
