'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
'
Namespace de.shk_connect.shkgh1
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AllgemeineAuskuenfteBeanBinding", [Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class allgemeineAuskuenfteService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetAllgemeineAuskunftOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SHK_Connect.My.MySettings.Default.SHK_Connect_de_shk_connect_shkgh1_allgemeineAuskuenfteService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetAllgemeineAuskunftCompleted As GetAllgemeineAuskunftCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function GetAllgemeineAuskunft(<System.Xml.Serialization.XmlElementAttribute("GetAllgemeineAuskunft", [Namespace]:="http://service.shk-connect.de")> ByVal GetAllgemeineAuskunft1 As GetAllgemeineAuskunft) As <System.Xml.Serialization.XmlElementAttribute("GetAllgemeineAuskunftAntwort", [Namespace]:="http://service.shk-connect.de")> GetAllgemeineAuskunftResponse
            Dim results() As Object = Me.Invoke("GetAllgemeineAuskunft", New Object() {GetAllgemeineAuskunft1})
            Return CType(results(0),GetAllgemeineAuskunftResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAllgemeineAuskunftAsync(ByVal GetAllgemeineAuskunft1 As GetAllgemeineAuskunft)
            Me.GetAllgemeineAuskunftAsync(GetAllgemeineAuskunft1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAllgemeineAuskunftAsync(ByVal GetAllgemeineAuskunft1 As GetAllgemeineAuskunft, ByVal userState As Object)
            If (Me.GetAllgemeineAuskunftOperationCompleted Is Nothing) Then
                Me.GetAllgemeineAuskunftOperationCompleted = AddressOf Me.OnGetAllgemeineAuskunftOperationCompleted
            End If
            Me.InvokeAsync("GetAllgemeineAuskunft", New Object() {GetAllgemeineAuskunft1}, Me.GetAllgemeineAuskunftOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAllgemeineAuskunftOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAllgemeineAuskunftCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAllgemeineAuskunftCompleted(Me, New GetAllgemeineAuskunftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class GetAllgemeineAuskunft
        
        Private schnittstellenversionField As String
        
        Private softwarenameField As String
        
        Private softwarepasswortField As String
        
        Private prozessField As String
        
        Private brancheIDField As String
        
        Private umkreisField As Umkreis
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Schnittstellenversion() As String
            Get
                Return Me.schnittstellenversionField
            End Get
            Set
                Me.schnittstellenversionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Softwarename() As String
            Get
                Return Me.softwarenameField
            End Get
            Set
                Me.softwarenameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Softwarepasswort() As String
            Get
                Return Me.softwarepasswortField
            End Get
            Set
                Me.softwarepasswortField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Prozess() As String
            Get
                Return Me.prozessField
            End Get
            Set
                Me.prozessField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BrancheID() As String
            Get
                Return Me.brancheIDField
            End Get
            Set
                Me.brancheIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Umkreis() As Umkreis
            Get
                Return Me.umkreisField
            End Get
            Set
                Me.umkreisField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class Umkreis
        
        Private postleitzahlField As String
        
        Private entfernungField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Postleitzahl() As String
            Get
                Return Me.postleitzahlField
            End Get
            Set
                Me.postleitzahlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Entfernung() As String
            Get
                Return Me.entfernungField
            End Get
            Set
                Me.entfernungField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class Unternehmen
        
        Private idField As Integer
        
        Private nameField As String
        
        Private strasseField As String
        
        Private pLZField As String
        
        Private ortField As String
        
        Private landField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ID() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Strasse() As String
            Get
                Return Me.strasseField
            End Get
            Set
                Me.strasseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PLZ() As String
            Get
                Return Me.pLZField
            End Get
            Set
                Me.pLZField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ort() As String
            Get
                Return Me.ortField
            End Get
            Set
                Me.ortField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Land() As String
            Get
                Return Me.landField
            End Get
            Set
                Me.landField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class Status
        
        Private codeField As String
        
        Private meldungField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Meldung() As String
            Get
                Return Me.meldungField
            End Get
            Set
                Me.meldungField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.shk-connect.de")>  _
    Partial Public Class GetAllgemeineAuskunftResponse
        
        Private schnittstellenversionField As String
        
        Private serverkennungField As String
        
        Private statusField As Status
        
        Private unternehmenField() As Unternehmen
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Schnittstellenversion() As String
            Get
                Return Me.schnittstellenversionField
            End Get
            Set
                Me.schnittstellenversionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Serverkennung() As String
            Get
                Return Me.serverkennungField
            End Get
            Set
                Me.serverkennungField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Status() As Status
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Unternehmen", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Unternehmen() As Unternehmen()
            Get
                Return Me.unternehmenField
            End Get
            Set
                Me.unternehmenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetAllgemeineAuskunftCompletedEventHandler(ByVal sender As Object, ByVal e As GetAllgemeineAuskunftCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAllgemeineAuskunftCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetAllgemeineAuskunftResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetAllgemeineAuskunftResponse)
            End Get
        End Property
    End Class
End Namespace
