'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.18052
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
'''<summary>
'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class XRDesignRibbonControllerResources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ClausSoftware.HWLInterops.XRDesignRibbonControllerResources", GetType(XRDesignRibbonControllerResources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreview() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ClosePreview", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreviewLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ClosePreviewLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Customize() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Customize", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_CustomizeLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_CustomizeLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Document() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Document", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMap() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_DocumentMap", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMapLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_DocumentMapLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHF() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_EditPageHF", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHFLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_EditPageHFLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsv() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportCsv", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsvLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportCsvLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportFile() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportFile", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportFileLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportFileLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphic() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportGraphic", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphicLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportGraphicLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtm() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportHtm", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtmLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportHtmLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportMht() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportMht", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportMhtLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportMhtLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdf() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportPdf", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdfLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportPdfLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtf() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportRtf", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtfLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportRtfLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxt() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportTxt", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxtLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportTxtLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportXls() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportXls", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_FillBackground() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_FillBackground", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_FillBackgroundLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_FillBackgroundLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Find() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Find", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_FindLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_FindLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_HandTool() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_HandTool", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Magnifier() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Magnifier", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePages() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_MultiplePages", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePagesLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_MultiplePagesLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Open() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Open", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_OpenLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_OpenLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMargins() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMargins", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsModerate() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsModerate", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNarrow() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNarrow", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNormal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNormal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsWide() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsWide", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientation() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientation", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLandscape() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLandscape", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationPortrait() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationPortrait", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PageSetupDialog() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageSetupDialog", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A4() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A4", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A5() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A5", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A6() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A6", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Executive() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Executive", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Legal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Legal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Letter() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Letter", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Tabloid() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Tabloid", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperSize() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperSize", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperSizeLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperSizeLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Parameters() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Parameters", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ParametersLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ParametersLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Pointer() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Pointer", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Print() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Print", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirect() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintDirect", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirectLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintDirectLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PrintLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetup() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintSetup", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetupLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintSetupLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Save() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Save", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SaveLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SaveLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Scale() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Scale", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ScaleLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ScaleLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendCsv() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendCsv", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendCsvLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendCsvLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendFile() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendFile", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendFileLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendFileLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphic() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendGraphic", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphicLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendGraphicLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendMht() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendMht", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendMhtLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendMhtLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendPdf() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendPdf", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendPdfLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendPdfLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendRtf() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendRtf", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendRtfLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendRtfLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendTxt() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendTxt", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendTxtLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendTxtLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendXls() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendXls", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendXlsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPageLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPageLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowLastPage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPageLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowLastPageLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowNextPage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPageLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowNextPageLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPageLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPageLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Watermark() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Watermark", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_WatermarkLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_WatermarkLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_Zoom() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Zoom", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ZoomIn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomIn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ZoomInLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomInLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ZoomLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOut() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomOut", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOutLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomOutLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignBottom() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignBottom", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignHorizontalCenters() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignHorizontalCenters", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignLeft() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignLeft", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignRight() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignRight", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignToGrid() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignToGrid", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignTop() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignTop", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_AlignVerticalCenters() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_AlignVerticalCenters", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_BackColor() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_BackColor", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_BringToFront() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_BringToFront", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_CenterHorizontally() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_CenterHorizontally", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_CenterVertically() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_CenterVertically", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Copy() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Copy", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_CopyLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_CopyLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Cut() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Cut", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_CutLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_CutLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Edit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Edit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Font() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Font", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_FontBold() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_FontBold", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_FontItalic() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_FontItalic", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_FontUnderline() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_FontUnderline", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ForeColor() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ForeColor", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HorizSpaceConcatenate() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceConcatenate", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HorizSpaceDecrease() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceDecrease", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HorizSpaceIncrease() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceIncrease", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HorizSpaceMakeEqual() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceMakeEqual", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlBackward() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlBackward", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlBackwardLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlBackwardLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlFind() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlFind", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlFindLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlFindLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlForward() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlForward", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlForwardLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlForwardLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlHome() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlHome", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlHomeLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlHomeLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlRefresh() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlRefresh", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlRefreshLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlRefreshLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlStop() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlStop", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_HtmlStopLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_HtmlStopLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_JustifyCenter() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_JustifyCenter", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_JustifyJustify() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_JustifyJustify", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_JustifyLeft() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_JustifyLeft", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_JustifyRight() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_JustifyRight", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_NewReport() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_NewReport", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_NewReportLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_NewReportLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_NewReportWizard() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_NewReportWizard", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_NewReportWizardLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_NewReportWizardLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_OpenFile() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_OpenFile", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_OpenFileLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_OpenFileLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Paste() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Paste", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_PasteLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_PasteLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Redo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Redo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_RedoLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_RedoLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Report() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Report", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SaveFile() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SaveFile", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SaveFileAs() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SaveFileAs", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SaveFileAsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SaveFileAsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SaveFileLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SaveFileLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SendToBack() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SendToBack", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SizeToControl() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SizeToControl", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SizeToControlHeight() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SizeToControlHeight", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SizeToControlWidth() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SizeToControlWidth", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_SizeToGrid() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_SizeToGrid", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Undo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Undo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_UndoLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_UndoLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_VertSpaceConcatenate() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceConcatenate", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_VertSpaceDecrease() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceDecrease", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_VertSpaceIncrease() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceIncrease", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_VertSpaceMakeEqual() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceMakeEqual", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Windows() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Windows", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_WindowsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_WindowsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_Zoom() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_Zoom", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ZoomIn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ZoomIn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ZoomInLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ZoomInLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ZoomLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ZoomLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ZoomOut() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ZoomOut", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property RibbonUserDesigner_ZoomOutLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonUserDesigner_ZoomOutLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
